#!/usr/bin/env python3
"""Render ARROW's four main LaTeX tables from the semantic registry."""

from __future__ import annotations

import csv
import json
import math
import statistics
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
REGISTRY_PATH = PAPER / "data" / "paper_numbers.json"


class Registry:
    def __init__(self) -> None:
        self.payload = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
        self.numbers = self.payload["numbers"]
        self.used: dict[str, dict[str, Any]] = {}

    def item(self, key: str) -> dict[str, Any]:
        item = self.numbers[key]
        self.used[key] = item
        return item

    def value(self, key: str) -> float:
        return float(self.item(key)["value"])

    def sd_from_seeds(self, key: str) -> float:
        values = list(self.item(key)["by_seed"].values())
        return statistics.stdev(float(value) for value in values)

    def reset_used(self) -> None:
        self.used = {}


def pct(value: float, digits: int = 2) -> str:
    return f"{100.0 * value:.{digits}f}"


def frac(value: float, digits: int = 4) -> str:
    return f"{value:.{digits}f}"


def signed_pp(value: float, digits: int = 2) -> str:
    return f"{100.0 * value:+.{digits}f}"


def kparams(value: float) -> str:
    return "--" if value < 0 else ("0" if value == 0 else f"{value / 1000.0:.1f}")


def write_table(name: str, body: str, registry: Registry) -> None:
    table_path = PAPER / "tables" / f"{name}.tex"
    table_path.write_text(body.rstrip() + "\n", encoding="utf-8")
    csv_path = PAPER / "data" / "table_sources" / f"{name}.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    columns = [
        "key", "value", "unit", "surface", "status", "source_path",
        "source_sha256", "source_json_path", "notes",
    ]
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, lineterminator="\n")
        writer.writeheader()
        for key in sorted(registry.used):
            item = registry.used[key]
            writer.writerow({column: item.get(column) for column in columns})


def write_supp_table(name: str, body: str, registry: Registry) -> None:
    table_path = PAPER / "supplement" / "tables" / f"{name}.tex"
    table_path.parent.mkdir(parents=True, exist_ok=True)
    table_path.write_text(body.rstrip() + "\n", encoding="utf-8")
    csv_path = PAPER / "data" / "table_sources" / f"{name}.csv"
    columns = [
        "key", "value", "unit", "surface", "status", "source_path",
        "source_sha256", "source_json_path", "notes",
    ]
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, lineterminator="\n")
        writer.writeheader()
        for key in sorted(registry.used):
            item = registry.used[key]
            writer.writerow({column: item.get(column) for column in columns})


def table1(reg: Registry) -> None:
    reg.reset_used()
    test_ci = [pct(float(v)) for v in reg.item("main.test5.gain")["ci95"]]
    strict_ci = [pct(float(v)) for v in reg.item("main.strict2031.gain")["ci95"]]
    rows = [
        (
            "Frozen base",
            pct(reg.value("main.test5.frozen_base")),
            pct(reg.value("main.strict2031.frozen_base")),
            "--", "--", "--", "--",
        ),
        (
            "Admission + Ranking",
            pct(reg.value("main.test5.arrow")),
            "--",
            rf"{signed_pp(reg.value('main.test5.gain'))} [{test_ci[0]}, {test_ci[1]}]",
            "--",
            pct(reg.value("anatomy.eligible_gt_recall50")),
            f"{reg.value('anatomy.mean_eligible_queries'):.1f}",
        ),
        (
            "ARROW-U2 (+ Abstention)",
            pct(reg.value("main.test5.arrow")),
            pct(reg.value("main.strict2031.arrow")),
            rf"{signed_pp(reg.value('main.test5.gain'))} [{test_ci[0]}, {test_ci[1]}]",
            rf"{pct(reg.value('main.strict2031.gain'))} [{strict_ci[0]}, {strict_ci[1]}]",
            pct(reg.value("anatomy.eligible_gt_recall50")),
            f"{reg.value('anatomy.mean_eligible_queries'):.1f}",
        ),
    ]
    body_rows = "\n".join(" & ".join(row) + r" \\" for row in rows)
    body = rf"""% Generated by paper/scripts/make_main_tables.py.
\begin{{table*}}[t]
\centering
\caption{{Held-out system endpoints.  Admission and Ranking determine the
localization route; adding Abstention leaves every selected query and box
bitwise unchanged.  Deltas and paired 95\% image-cluster intervals are relative
to the frozen base.}}
\label{{tab:headline}}
\scriptsize
\setlength{{\tabcolsep}}{{3.1pt}}
\begin{{tabular}}{{lrrrrrr}}
\toprule
System & Test5$\uparrow$ & Strict FPR95$\downarrow$ & $\Delta$Test5 [CI] & FPR95 red. [CI] & Elig. recall$\uparrow$ & Elig. $n\downarrow$ \\
\midrule
{body_rows}
\bottomrule
\end{{tabular}}
\vspace{{2pt}}
\parbox{{0.98\textwidth}}{{\footnotesize Percentages except eligible-query
count.  Frozen-to-ARROW rows are cumulative system comparisons with additional
head supervision; equal-supervision owner claims use
Tab.~\ref{{tab:interference}}.  Validation decomposition and parameter/runtime
accounting are supplementary.}}
\end{{table*}}
"""
    write_table("table1_main", body, reg)


def table2(reg: Registry) -> None:
    reg.reset_used()
    seeds = (17, 42, 73)

    def seed_mean_sd(prefix: str, metric: str) -> str:
        values = [reg.value(f"{prefix}.seed{seed}.{metric}") for seed in seeds]
        mean = statistics.mean(values)
        aggregate_metric = "strict2031_fpr95" if metric == "fpr95" else metric
        registered_mean = reg.value(f"{prefix}.{aggregate_metric}")
        registered_sd = reg.value(f"{prefix}.{aggregate_metric}_sd")
        if not math.isclose(mean, registered_mean, rel_tol=0.0, abs_tol=1e-12):
            raise RuntimeError(f"aggregate drift for {prefix}.{metric}")
        return rf"{pct(registered_mean, 3)} $\pm$ {pct(registered_sd, 3)}"

    def registered_mean_sd(prefix: str, metric: str) -> str:
        item = reg.item(f"{prefix}.{metric}")
        mean = pct(float(item["value"]), 3)
        sd = item.get("sample_sd")
        return mean if sd is None else rf"{mean} $\pm$ {pct(float(sd), 3)}"

    frozen_rows = [
        (
            "Shared-Wide",
            f"{int(reg.value('b58_capacity.shared_wide.score_owner_parameters')):,}",
            f"{int(reg.value('b58_capacity.shared_wide.score_macs_per_query_and_output')):,}",
            "/".join(
                pct(reg.value(f"b58_capacity.shared_wide.seed{seed}.negative_cosine_fraction"), 1)
                for seed in seeds
            ),
            "/".join(
                f"{reg.value(f'b58_capacity.shared_wide.seed{seed}.cosine_min'):+.3f}"
                for seed in seeds
            ),
            seed_mean_sd("b58_capacity.shared_wide", "test5"),
            seed_mean_sd("b58_capacity.shared_wide", "fpr95"),
        ),
        (
            "Isolated",
            f"{int(reg.value('b58_capacity.isolated.score_owner_parameters')):,}",
            f"{int(reg.value('b58_capacity.isolated.score_macs_per_query_and_output')):,}",
            "0/0/0", "no path",
            seed_mean_sd("b58_capacity.isolated", "test5"),
            seed_mean_sd("b58_capacity.isolated", "fpr95"),
        ),
    ]

    strong_rows = [
        (
            "GDINO parent", "Native", "--", "--",
            pct(reg.value("original_parent.native.test5"), 3),
            pct(reg.value("original_parent.native.testab"), 3),
            pct(reg.value("original_parent.native.strict_fpr95"), 3),
        ),
        (
            "GDINO parent", "Shared-Wide",
            pct(reg.value("original_parent.shared_wide.u150.p_negative"), 1),
            f"{reg.value('original_parent.shared_wide.u150.q05'):+.3f}",
            registered_mean_sd("original_parent.shared_wide", "test5"),
            registered_mean_sd("original_parent.shared_wide", "testab"),
            registered_mean_sd("original_parent.shared_wide", "strict_fpr95"),
        ),
        (
            "GDINO parent", "Isolated", "0.0", "no path",
            registered_mean_sd("original_parent.isolated_128", "test5"),
            registered_mean_sd("original_parent.isolated_128", "testab"),
            registered_mean_sd("original_parent.isolated_128", "strict_fpr95"),
        ),
        (
            "Adapted", "Native", "--", "--",
            pct(reg.value("b58_raw_query.native.test5"), 3),
            pct(reg.value("b58_raw_query.native.testab"), 3),
            pct(reg.value("b58_raw_query.native.strict_fpr95"), 3),
        ),
        (
            "Adapted", "Shared-Wide",
            pct(reg.value("b58_raw_query.shared_wide.u150.p_negative"), 1),
            f"{reg.value('b58_raw_query.shared_wide.u150.q05'):+.3f}",
            registered_mean_sd("b58_raw_query.shared_wide", "test5"),
            registered_mean_sd("b58_raw_query.shared_wide", "testab"),
            registered_mean_sd("b58_raw_query.shared_wide", "strict_fpr95"),
        ),
        (
            "Adapted", "Isolated", "0.0", "no path",
            registered_mean_sd("b58_raw_query.isolated_128", "test5"),
            registered_mean_sd("b58_raw_query.isolated_128", "testab"),
            registered_mean_sd("b58_raw_query.isolated_128", "strict_fpr95"),
        ),
    ]

    frozen_body = "\n".join(" & ".join(row) + r" \\" for row in frozen_rows)
    strong_body = "\n".join(" & ".join(row) + r" \\" for row in strong_rows)

    frozen_rec = reg.item("b58_capacity.isolated_minus_shared_wide.test5_gain")
    frozen_fpr = reg.item("b58_capacity.isolated_minus_shared_wide.strict2031_fpr95_gain")
    frozen_rec_ci = frozen_rec["ci95"]
    frozen_fpr_ci = frozen_fpr["ci95"]

    parent_prefix = "original_parent.contrast.isolated_vs_shared_wide"
    parent_rec = reg.item(f"{parent_prefix}.testab_gain")
    parent_fpr = reg.item(f"{parent_prefix}.fpr95_gain")
    contrast_rows = [(
        "GDINO parent: Isolated $-$ Shared-Wide",
        rf"{signed_pp(float(parent_rec['value']), 3)} [{pct(parent_rec['ci95'][0], 3)}, {pct(parent_rec['ci95'][1], 3)}]",
        rf"{signed_pp(float(parent_fpr['value']), 3)} [{pct(parent_fpr['ci95'][0], 3)}, {pct(parent_fpr['ci95'][1], 3)}]",
        f"{reg.value(f'{parent_prefix}.iut_p'):.4f}",
        "fail",
    )]
    b58_prefix = "b58_raw_query.contrast.isolated_vs_shared_wide"
    b58_rec = reg.item(f"{b58_prefix}.testab_gain")
    b58_fpr = reg.item(f"{b58_prefix}.fpr95_gain")
    contrast_rows.append((
        "Adapted: Isolated $-$ Shared-Wide",
        rf"{signed_pp(float(b58_rec['value']), 3)} [{pct(b58_rec['ci95'][0], 3)}, {pct(b58_rec['ci95'][1], 3)}]",
        rf"{signed_pp(float(b58_fpr['value']), 3)} [{pct(b58_fpr['ci95'][0], 3)}, {pct(b58_fpr['ci95'][1], 3)}]",
        f"{reg.value(f'{b58_prefix}.iut_p'):.4f}",
        "fail",
    ))
    contrast_body = "\n".join(" & ".join(row) + r" \\" for row in contrast_rows)
    body = rf"""% Generated by paper/scripts/make_main_tables.py.
\begin{{table*}}[t]
\centering
\caption{{Representation-dependent interference under capacity-matched owner
controls.  Entries are final three-seed mean $\pm$ sample SD, followed by the
preplanned paired image-cluster contrasts with 95\% bootstrap intervals.}}
\label{{tab:interference}}
\scriptsize
\setlength{{\tabcolsep}}{{3.0pt}}
\textbf{{(a) Frozen-base representation}}\\[2pt]
\begin{{tabular}}{{lrrrrrr}}
\toprule
Owner & Params & MAC/query & Neg. probes (\%) & Min. cosine & Test5$\uparrow$ & FPR95$\downarrow$ \\
\midrule
{frozen_body}
\bottomrule
\end{{tabular}}
\\[2pt]
\parbox{{0.97\textwidth}}{{\scriptsize Paired Isolated$-$Shared-Wide: Test5
{signed_pp(float(frozen_rec['value']), 3)} pp
[${pct(frozen_rec_ci['ci95_low'], 3)}$, ${pct(frozen_rec_ci['ci95_high'], 3)}$],
$p={frozen_rec_ci['one_sided_p_gain_le_margin']:.4f}$; FPR95 reduction
{signed_pp(float(frozen_fpr['value']), 3)} pp
[${pct(frozen_fpr_ci['ci95_low'], 3)}$, ${pct(frozen_fpr_ci['ci95_high'], 3)}$],
$p={frozen_fpr_ci['one_sided_p_gain_le_margin']:.3f}$. Joint gate: \textbf{{fail}}.}}
\\[5pt]
\textbf{{(b) Strict same-head parent $\rightarrow$ adapted axis}}\\[2pt]
\begin{{tabular}}{{llrrrrr}}
\toprule
Frozen trunk & Owner & $P(\cos<0)$ (\%) & U150 q05 & Test5$\uparrow$ & TestAB$\uparrow$ & FPR95$\downarrow$ \\
\midrule
{strong_body}
\bottomrule
\end{{tabular}}
\\[3pt]
\begin{{tabular}}{{lrrrc}}
\toprule
Planned contrast & $\Delta$REC [95\% CI] & FPR95 reduction [95\% CI] & IUT $p$ & Gate \\
\midrule
{contrast_body}
\bottomrule
\end{{tabular}}
\vspace{{2pt}}
\parbox{{0.98\textwidth}}{{\footnotesize Percentages; deltas are points and
positive FPR95 reduction favors Isolated. Learned rows are fixed U150,
three-seed mean $\pm$ SD; every bootstrap replicate recomputes positive q05.
Shared-Wide/Isolated have 100,362/100,358 parameters and matched optimization.
Parent/adapted use identical 100k heads.  Ownership-effect DiD:
{signed_pp(reg.value('parent_to_b58_did.test5'), 3)} pp Test5
[${pct(reg.item('parent_to_b58_did.test5')['ci95'][0], 3)}$,
${pct(reg.item('parent_to_b58_did.test5')['ci95'][1], 3)}$] and
{signed_pp(reg.value('parent_to_b58_did.fpr95_reduction'), 3)} pp FPR95
(CI crosses zero). MM controls are supplementary.}}
\end{{table*}}
"""
    write_table("table2_ownership", body, reg)


def table3(reg: Registry) -> None:
    reg.reset_used()
    rows = []
    for route, label in (
        ("arrow_v", "Visual support"),
        ("arrow_t", "Category text"),
        ("arrow_n", "Learned null"),
    ):
        test_key = f"admission_input.{route}.test5"
        switch_key = f"admission_input.{route}.switch_success"
        sd = reg.sd_from_seeds(test_key) if "by_seed" in reg.item(test_key) else math.nan
        test_cell = pct(reg.value(test_key))
        if not math.isnan(sd):
            test_cell += rf" $\pm$ {pct(sd)}"
        rows.append((
            label,
            test_cell,
            pct(reg.value(switch_key)),
            pct(reg.value(f"finecops.matched.{route}.positive_p1_macro")),
            pct(reg.value(f"finecops.matched.{route}.negative_text_recall1")),
            pct(reg.value(f"finecops.matched.{route}.negative_image_recall1")),
        ))
    body_rows = "\n".join(" & ".join(row) + r" \\" for row in rows)
    coverage = pct(reg.value("finecops.arrow_v.support_coverage"))
    visual_text = reg.item("admission_input.visual_over_text.switch_gain")
    text_null = reg.item("admission_input.text_over_null.switch_gain")
    body = rf"""% Generated by paper/scripts/make_main_tables.py.
\begin{{table}}[t]
\centering
\caption{{Admission cues.  FineCops columns use one exact-support matched
surface; the switch panel changes only the named category cue.}}
\label{{tab:admission}}
\scriptsize
\setlength{{\tabcolsep}}{{0.8pt}}
\begin{{tabular}}{{lccccc}}
\toprule
Cue & Test5$\uparrow$ & Switch$\uparrow$ & P@1$\uparrow$ & Text R@1$\uparrow$ & Image R@1$\uparrow$ \\
\midrule
{body_rows}
\bottomrule
\end{{tabular}}
\vspace{{2pt}}
\parbox{{0.98\columnwidth}}{{\scriptsize Percentages; Test5 is mean $\pm$
sample SD over all three seeds. Visual$-$text switch gain is
{signed_pp(float(visual_text['value']))} pp
[${pct(visual_text['ci95'][0])}$, ${pct(visual_text['ci95'][1])}$];
text$-$null is {signed_pp(float(text_null['value']))} pp
[${pct(text_null['ci95'][0])}$, ${pct(text_null['ci95'][1])}$]. Visual-support
coverage is {coverage}\%; unsupported rows are never counted as rejection.}}
\end{{table}}
"""
    write_table("table3_admission", body, reg)


def table4(reg: Registry) -> None:
    reg.reset_used()
    fine_rows = [(
        "MM-GDINO-T (published)",
        pct(reg.value("finecops.published_mmgdino.positive_p1_macro")),
        pct(reg.value("finecops.published_mmgdino.negative_text_recall1")),
        pct(reg.value("finecops.published_mmgdino.negative_image_recall1")),
        pct(reg.value("finecops.published_mmgdino.negative_text_auroc_type_macro")),
        pct(reg.value("finecops.published_mmgdino.negative_image_auroc_type_macro")),
    ), (
        "Original GDINO-T (local)",
        pct(reg.value("finecops.original_ogc.native_max.positive_p1_macro")),
        pct(reg.value("finecops.original_ogc.native_max.negative_text_recall1")),
        pct(reg.value("finecops.original_ogc.native_max.negative_image_recall1")),
        pct(reg.value("finecops.original_ogc.native_max.negative_text_auroc_type_macro")),
        pct(reg.value("finecops.original_ogc.native_max.negative_image_auroc_type_macro")),
    )]
    for route, label in (
        ("frozen_base", "Frozen base"),
        ("ranker_rejector", "Ranking + Abstention"),
    ):
        auc_route = "frozen_base" if route == "frozen_base" else "isolated_rejector"
        fine_rows.append((
            label,
            pct(reg.value(f"finecops.{route}.positive_p1_macro")),
            pct(reg.value(f"finecops.{route}.negative_text_recall1")),
            pct(reg.value(f"finecops.{route}.negative_image_recall1")),
            pct(reg.value(f"finecops.official_exact.{auc_route}.negative_text_auroc_type_macro")),
            pct(reg.value(f"finecops.official_exact.{auc_route}.negative_image_auroc_type_macro")),
        ))
    fine_body = "\n".join(" & ".join(row) + r" \\" for row in fine_rows)

    gref_rows = []
    for surface, surface_label in (("full", "Full restricted"), ("rejector_supervision_disjoint", "Rejector-supervision-disjoint")):
        for route, route_label in (("frozen_base", "Frozen base"), ("isolated_rejector", "Isolated rejector")):
            fixed = "--" if route == "frozen_base" else pct(reg.value(f"gref.{surface}.{route}.fixed_tpr"))
            gref_rows.append((
                ({"Full restricted": "Full", "Rejector-supervision-disjoint": "Rej.-sup.-disj."}[surface_label]) if route == "frozen_base" else "",
                {"Frozen base": "Base", "Isolated rejector": "Rejector"}[route_label],
                pct(reg.value(f"gref.{surface}.{route}.auroc")),
                pct(reg.value(f"gref.{surface}.{route}.aupr")),
                pct(reg.value(f"gref.{surface}.{route}.fpr95")),
                fixed,
            ))
    gref_body = "\n".join(" & ".join(row) + r" \\" for row in gref_rows)
    body = rf"""% Generated by paper/scripts/make_main_tables.py.
\begin{{table}}[t]
\centering
\caption{{External rejection transfer. FineCops uses standard expression-only
inputs; gRefCOCO is explicitly restricted to single-target/no-target rows.}}
\label{{tab:external}}
\textbf{{(a) FineCops-Ref full test}}\\[2pt]
\scriptsize
\setlength{{\tabcolsep}}{{1.0pt}}
\begin{{tabular}}{{lccccc}}
\toprule
Route & P@1$\uparrow$ & T R@1$\uparrow$ & I R@1$\uparrow$ & T AUC$\uparrow$ & I AUC$\uparrow$ \\
\midrule
{fine_body}
\bottomrule
\end{{tabular}}
\\[5pt]
\textbf{{(b) gRefCOCO rejection transfer}}\\[2pt]
\scriptsize
\begin{{tabular}}{{llcccc}}
\toprule
Slice & Route & AUROC$\uparrow$ & AUPR$\uparrow$ & FPR95$\downarrow$ & Fixed TPR \\
\midrule
{gref_body}
\bottomrule
\end{{tabular}}
\\[-1pt]
\parbox{{0.98\columnwidth}}{{\scriptsize T/I denote negative text/image.
The published MM-GDINO-T row is context, not a local or paired comparison.
The local original row loads the unmodified OGC checkpoint with its native
max-token score.  AUC uses the pinned official evaluator's historical
level-1-positive scope for every FineCops row. Fixed TPR uses the sealed source
source threshold; it is never refit. Multi-target gRefCOCO is excluded.}}
\end{{table}}
"""
    write_table("table4_external", body, reg)


def number_macros(reg: Registry) -> None:
    reg.reset_used()
    values = {
        "ArrowTestGain": signed_pp(reg.value("main.test5.gain")),
        "ArrowTestGainLo": pct(reg.item("main.test5.gain")["ci95"][0]),
        "ArrowTestGainHi": pct(reg.item("main.test5.gain")["ci95"][1]),
        "ArrowStrictGain": pct(reg.value("main.strict2031.gain")),
        "ArrowStrictGainLo": pct(reg.item("main.strict2031.gain")["ci95"][0]),
        "ArrowStrictGainHi": pct(reg.item("main.strict2031.gain")["ci95"][1]),
        "ArrowOwnershipStrictGain": pct(reg.value("ownership.o2_minus_o0.strict_fpr95_reduction")),
        "ArrowVisualSwitch": pct(reg.value("admission_input.arrow_v.switch_success"), 1),
        "ArrowTextSwitch": pct(reg.value("admission_input.arrow_t.switch_success"), 1),
        "ArrowNullSwitch": pct(reg.value("admission_input.arrow_n.switch_success"), 1),
        "ArrowFineCopsCoverage": pct(reg.value("finecops.arrow_v.support_coverage"), 2),
        "ArrowFineCopsFixedTPR": pct(reg.value("finecops.arrow_t.fixed_tpr"), 2),
        "ArrowGrefFixedTPR": pct(reg.value("gref.full.isolated_rejector.fixed_tpr"), 2),
        "OriginalOgcNativeP": pct(reg.value("finecops.original_ogc.native_max.positive_p1_macro")),
        "OriginalOgcNativeTextR": pct(reg.value("finecops.original_ogc.native_max.negative_text_recall1")),
        "OriginalOgcNativeImageR": pct(reg.value("finecops.original_ogc.native_max.negative_image_recall1")),
        "OriginalOgcNativeTextAuc": pct(reg.value("finecops.original_ogc.native_max.negative_text_auroc_type_macro")),
        "OriginalOgcNativeImageAuc": pct(reg.value("finecops.original_ogc.native_max.negative_image_auroc_type_macro")),
        "OriginalOgcMeanP": pct(reg.value("finecops.original_ogc.matched_mean.positive_p1_macro")),
        "OriginalOgcMeanTextR": pct(reg.value("finecops.original_ogc.matched_mean.negative_text_recall1")),
        "OriginalOgcMeanImageR": pct(reg.value("finecops.original_ogc.matched_mean.negative_image_recall1")),
        "OriginalOgcMeanTextAuc": pct(reg.value("finecops.original_ogc.matched_mean.negative_text_auroc_type_macro")),
        "OriginalOgcMeanImageAuc": pct(reg.value("finecops.original_ogc.matched_mean.negative_image_auroc_type_macro")),
    }
    lines = ["% Generated by paper/scripts/make_main_tables.py."]
    lines.extend(rf"\newcommand{{\{key}}}{{{value}}}" for key, value in values.items())
    (PAPER / "data" / "generated_numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def supplement_cumulative_routes(reg: Registry) -> None:
    """Keep the implementation ladder out of the main causal argument."""
    reg.reset_used()
    rows = [
        (
            "Frozen base",
            pct(reg.value("main.test5.frozen_base")),
            pct(reg.value("main.strict2031.frozen_base")), "--", "--",
            kparams(reg.value("efficiency.route.frozen_base.active_params")),
            kparams(reg.value("efficiency.route.frozen_base.cumulative_params")),
        ),
        (
            "+ complete-expression Ranking", "--", "--", "--", "--",
            kparams(reg.value("efficiency.route.ranker.active_params")),
            kparams(reg.value("efficiency.route.ranker.cumulative_params")),
        ),
        (
            r"+ static Admission$^{\dagger}$", "--", "--", "--", "--", "0",
            kparams(reg.value("efficiency.route.static_admission.cumulative_params")),
        ),
        (
            "+ learned Admission",
            pct(reg.value("main.test5.arrow")), "--",
            pct(reg.value("anatomy.eligible_gt_recall50")),
            f"{reg.value('anatomy.mean_eligible_queries'):.1f}",
            kparams(reg.value("efficiency.route.learned_admission.active_params")),
            kparams(reg.value("efficiency.route.learned_admission.cumulative_params")),
        ),
        (
            "+ isolated Abstention (ARROW-U2)",
            pct(reg.value("main.test5.arrow")),
            pct(reg.value("main.strict2031.arrow")),
            pct(reg.value("anatomy.eligible_gt_recall50")),
            f"{reg.value('anatomy.mean_eligible_queries'):.1f}",
            kparams(reg.value("efficiency.route.full_arrow.active_params")),
            kparams(reg.value("efficiency.route.full_arrow.cumulative_params")),
        ),
    ]
    body_rows = "\n".join(" & ".join(row) + r" \\" for row in rows)
    body = rf"""% Generated by paper/scripts/make_main_tables.py.
\begin{{table*}}[t]
\centering
\caption{{Cumulative implementation ladder.  It documents how the released
system was assembled; it is not an equal-supervision or equal-capacity causal
comparison.}}
\label{{tab:supp-cumulative-routes}}
\scriptsize
\setlength{{\tabcolsep}}{{4pt}}
\begin{{tabular}}{{lrrrrrr}}
\toprule
Route & Test5$\uparrow$ & FPR95$\downarrow$ & Elig. recall$\uparrow$ & Elig. $n\downarrow$ & Active (K) & Cumulative (K) \\
\midrule
{body_rows}
\bottomrule
\end{{tabular}}
\parbox{{0.97\textwidth}}{{\scriptsize Percentages except eligible count and
parameter columns. Admission+Ranking and the full system have bitwise-identical
queries, selected boxes, and localization records. $^\dagger$Static Admission
is validation-only, so no held-out endpoint is assigned.}}
\end{{table*}}
"""
    write_supp_table("supp_cumulative_routes", body, reg)


def supplement_training_table(reg: Registry) -> None:
    reg.reset_used()
    def mean_sd(key: str) -> str:
        return f"{pct(reg.value(key))} $\\pm$ {pct(float(reg.item(key)['sample_sd']))}"

    static_seed17 = pct(reg.value("admission_training.a0_a2.seed17_val3_micro"))
    admission_rows = [
        r"A0 & Frozen & Frozen & Off & Off & -- & -- \\",
        "A1 & Train & Frozen & On & On & "
        + mean_sd("admission_training.a1.val3_macro")
        + " & " + pct(reg.value("admission_training.a1.test5")) + r" \\",
        r"A2 & Frozen & Train & On & On & -- & -- \\",
        "A3 & Train & Train & On & Off & "
        + mean_sd("admission_training.a3.val3_macro") + r" & -- \\",
        "A4 & Train & Train & Off & On & "
        + mean_sd("admission_training.a4.val3_macro") + r" & -- \\",
        "A5 & Train & Train & On & On & "
        + mean_sd("admission_training.a5.val3_macro")
        + " & " + pct(reg.value("admission_training.a5.test5")) + r" \\",
    ]

    rejection_rows = [r"C0 & Identity & No & No & No & -- & -- & -- \\"]
    for row, objective, queue, trust, margin in (
        ("c1", "Batch negative", "No", "No", "No"),
        ("c2", "Negative FPR", "Yes", "No", "No"),
        ("c3", "Negative FPR", "Yes", "Yes", "No"),
        ("c4", "Negative FPR", "Yes", "Yes", "Yes"),
    ):
        fpr = f"rejection_training.{row}.fpr95"
        win = f"rejection_training.{row}.pair_win"
        strict = (
            pct(reg.value(f"rejection_training.{row}.strict2031_fpr95"))
            if row in {"c2", "c3"} else "--"
        )
        rejection_rows.append(
            f"{row.upper()} & {objective} & {queue} & {trust} & {margin} & "
            f"{mean_sd(fpr)} & {mean_sd(win)} & {strict} " + r"\\"
        )

    data_rows = [
        r"D0 & None (positive-only) & None & -- & -- & No-TN control \\",
        "D1 & Edited text & Unverified & "
        + mean_sd("rejection_training.d1.fpr95") + " & "
        + mean_sd("rejection_training.d1.pair_win") + r" & Stress control \\",
        "D3 & Proposal-covered pairs & Proposal-covered & "
        + mean_sd("rejection_training.c3.fpr95") + " & "
        + mean_sd("rejection_training.c3.pair_win") + r" & Main clean data \\",
    ]

    ownership_rows = []
    for row, owner, schedule, test_key, strict_key in (
        ("o0", "Shared scalar", "Interleaved", "ownership.o0.test5", "ownership.o0.strict2031_fpr95"),
        ("o1", "Separate heads/shared feature", "Interleaved", None, None),
        ("o2", "Isolated owners", "Interleaved", "ownership.o2.test5", "ownership.o2.strict2031_fpr95"),
        ("o3", "Isolated owners", "Phased", "ownership.o3.test5", "ownership.o3.strict2031_fpr95"),
    ):
        test = pct(reg.value(test_key)) if test_key else "--"
        strict = pct(reg.value(strict_key)) if strict_key else "--"
        ownership_rows.append(
            f"{row.upper()} & {owner} & {schedule} & "
            f"{mean_sd(f'ownership.{row}.val3_macro')} & "
            f"{mean_sd(f'ownership.{row}.calibration_fpr95')} & "
            f"{mean_sd(f'ownership.{row}.calibration_pair_win')} & "
            f"{test} & {strict} " + r"\\"
        )

    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Complete Admission training grid. Val3 is validation-only mechanism evidence; Test5 appears only for the preregistered A5--A1 contrast.}
\label{tab:supp-admission-grid}
\label{tab:supp-training}
\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{lcccccc}\toprule
ID & Surface & Aux. & Category-complete & Preserve & Val3 macro$\uparrow$ & Test5$\uparrow$\\\midrule
""" + "\n".join(admission_rows) + rf"""
\bottomrule\end{{tabular}}
\parbox{{0.97\textwidth}}{{\scriptsize Values are three-seed mean $\pm$ sample SD unless only a held-out mean is shown. A2's training-only auxiliary is never deployed and its three deployable checkpoints are bitwise equal to A0. The only sealed static-route score is a seed-17 Val3 micro value of {static_seed17}\%; it is not inserted into the three-seed macro column.}}
""" + r"""
\end{table*}

\begin{table*}[t]
\centering
\caption{Complete clean Abstention-objective grid and allowed data-provenance controls. Calibration rows are mechanism evidence. Strict-TN2031 was opened only for preregistered C3--C2; no row-specific checkpoint or milestone was selected.}
\label{tab:supp-rejection-grid}
\scriptsize
\setlength{\tabcolsep}{2.3pt}
\begin{tabular}{llcccccc}\toprule
ID & Objective & Queue? & Trust? & Margin? & Cal. FPR95$\downarrow$ & Pair win$\uparrow$ & Strict$\downarrow$\\\midrule
""" + "\n".join(rejection_rows) + r"""
\bottomrule\end{tabular}
\vspace{4pt}

\textbf{Data provenance controls}\par\smallskip
\begin{tabular}{llllll}\toprule
ID & Negative source & Verification scope & Cal. FPR95$\downarrow$ & Pair win$\uparrow$ & Role\\\midrule
""" + "\n".join(data_rows) + r"""
\bottomrule\end{tabular}
\parbox{0.97\textwidth}{\scriptsize C0/D0 have no independently trained absolute rejector, hence ``--''. D1 is an unverified weak-data stress control; D3 is the proposal-covered clean source used by C3. Historical rule-swap and approximate matched rows are excluded from manuscript tables.}
\end{table*}

\begin{table*}[t]
\centering
\caption{Complete ownership and scheduling block. Val3/calibration columns are mechanism evidence; held-out cells occur only for the preregistered O2--O0 and O3--O2 contrasts.}
\label{tab:supp-ownership-grid}
\scriptsize
\setlength{\tabcolsep}{2.4pt}
\begin{tabular}{lllccccc}\toprule
ID & Trainable topology & Schedule & Val3$\uparrow$ & Cal. FPR95$\downarrow$ & Pair win$\uparrow$ & Test5$\uparrow$ & Strict$\downarrow$\\\midrule
""" + "\n".join(ownership_rows) + r"""
\bottomrule\end{tabular}
\parbox{0.97\textwidth}{\scriptsize O0 has one shared deployed scalar; O1 separates outputs but retains a shared trainable feature; O2/O3 use exclusive owners. O2 establishes the ownership effect. The O3--O2 strict contrast is not significant, so phasing is not claimed as independently beneficial.}
\end{table*}
"""
    write_supp_table("supp_training_controls", body, reg)


def supplement_ref_breakdown_table(reg: Registry) -> None:
    reg.reset_used()
    rows = []
    for family, labels in (
        ("Admission", (("A1", "a1"), ("A3", "a3"), ("A4", "a4"), ("A5", "a5"))),
        ("Ownership", (("O0", "o0"), ("O1", "o1"), ("O2", "o2"), ("O3", "o3"))),
    ):
        prefix = "admission_training" if family == "Admission" else "ownership"
        for label, row in labels:
            values = [
                pct(reg.value(f"{prefix}.{row}.refcoco_val.mean")),
                pct(reg.value(f"{prefix}.{row}.refcocop_val.mean")),
                pct(reg.value(f"{prefix}.{row}.refcocog_val.mean")),
                *[
                    pct(reg.value(f"{prefix}.{row}.seed{seed}.val3_micro"))
                    for seed in (17, 42, 73)
                ],
            ]
            rows.append(" & ".join((family, label, *values)) + r" \\")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Per-split and per-seed Ref validation results for every trajectory with a sealed three-seed forward. Split columns average the three seeds; seed columns are pooled Val3 micro Acc@0.5. These are validation-only mechanism results.}
\label{tab:supp-ref-breakdown}
\scriptsize
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{llcccccc}\toprule
Block & ID & RefCOCO & RefCOCO+ & RefCOCOg & s17 & s42 & s73\\\midrule
""" + "\n".join(rows) + r"""
\bottomrule\end{tabular}
\parbox{0.97\textwidth}{\scriptsize A0/A2 are absent here because only deployment parity and a single-seed static route were sealed; reporting copied three-seed values would overstate the available evidence.}
\end{table*}
"""
    write_supp_table("supp_ref_breakdown", body, reg)


def supplement_gap_table(reg: Registry) -> None:
    reg.reset_used()
    rows = []
    total_n = int(reg.value("gap_sensitivity.gap_3.n"))
    for label, display in (
        ("0", "0"), ("0p5", "0.5"), ("1", "1"), ("2", "2"),
        ("3", "3"), ("5", "5"), ("10", "10"), ("infinity", r"$\infty$"),
    ):
        prefix = f"gap_sensitivity.gap_{label}"
        reg.value(f"{prefix}.gap")
        rows.append(
            f"{display} & {pct(reg.value(f'{prefix}.acc50'))} & "
            f"{pct(reg.value(f'{prefix}.eligible_recall50'))} & "
            f"{reg.value(f'{prefix}.mean_eligible_queries'):.1f} " + r"\\"
        )
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table}[t]
\centering
\caption{Relative Admission-gap sensitivity on the fixed seed-42 Val3 single forward. This exploratory sweep cannot change the sealed model.}
\label{tab:supp-gap}
\scriptsize
\setlength{\tabcolsep}{5pt}
\begin{tabular}{rrrr}\toprule
Gap & Acc$\uparrow$ & Elig. recall$\uparrow$ & Elig. candidates$\downarrow$\\\midrule
""" + "\n".join(rows) + r"""
\bottomrule\end{tabular}
""" + rf"""
\parbox{{0.96\columnwidth}}{{\scriptsize Accuracy and recall are percentages. Every value is pooled over {total_n:,} expressions. Candidate counts are recomputed from the immutable records referenced by the sealed sweep summary; their byte hashes are stored in the derived receipt.}}
\end{{table}}
"""
    write_supp_table("supp_gap_sensitivity", body, reg)


def supplement_finecops_subgroup_table(reg: Registry) -> None:
    reg.reset_used()
    positive_rows = []
    for level in (1, 2, 3):
        positive_rows.append(
            f"L{level} & {pct(reg.value(f'finecops.subgroup.frozen_base.positive_l{level}_p1'))} & "
            f"{pct(reg.value(f'finecops.subgroup.arrow_t.positive_l{level}_p1'))} " + r"\\"
        )
    subgroup_names = {
        "text": (
            ("Attribute", "L1"), ("Attribute", "L2"), ("Object", "L1"),
            ("Object", "L2"), ("Order", "L1"), ("Order", "L2"),
            ("Relation", "L1"), ("Relation", "L2"),
            ("Swap-attr.", "L1"), ("Swap-attr.", "L2"),
        ),
        "image": (
            ("Attribute", "L1"), ("Attribute", "L2"), ("Flip", "L1"),
            ("Flip", "L2"), ("Object", "L1"), ("Object", "L2"),
            ("Order", "L1"), ("Swap-attr.", "L1"), ("Swap-attr.", "L2"),
        ),
    }
    kind_rows: dict[str, list[str]] = {"text": [], "image": []}
    for kind, groups in subgroup_names.items():
        for name, level in groups:
            raw_name = name.lower().replace("-attr.", "_attr").replace(".", "")
            safe = f"{raw_name}_{level.lower()}"
            count = int(reg.value(f"finecops.subgroup.count.{kind}.{safe}"))
            base = pct(reg.value(f"finecops.subgroup.frozen_base.{kind}.{safe}.recall1"))
            arrow = pct(reg.value(f"finecops.subgroup.arrow_t.{kind}.{safe}.recall1"))
            kind_rows[kind].append(f"{name} & {level} & {count} & {base} & {arrow} " + r"\\")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{FineCops-Ref descriptive subgroup results (full-test routes; three-seed means). Only subgroups explicitly present in the sealed result object are shown. No subgroup threshold is fit.}
\label{tab:supp-finecops-subgroups}
\scriptsize
\centering\textbf{Positive difficulty}\par\smallskip
\begin{tabular}{lrr}\toprule
Level & Base P@1 & ARROW-T P@1\\\midrule
""" + "\n".join(positive_rows) + r"""
\bottomrule\end{tabular}
\par\medskip
\begin{minipage}[t]{0.48\textwidth}
\centering\textbf{Negative text}\par\smallskip
\begin{tabular}{llrrr}\toprule
Type & Level & $n$ & Base R@1 & ARROW-T R@1\\\midrule
""" + "\n".join(kind_rows["text"]) + r"""
\bottomrule\end{tabular}
\end{minipage}\hfill
\begin{minipage}[t]{0.48\textwidth}
\centering\textbf{Negative image}\par\smallskip
\begin{tabular}{llrrr}\toprule
Type & Level & $n$ & Base R@1 & ARROW-T R@1\\\midrule
""" + "\n".join(kind_rows["image"]) + r"""
\bottomrule\end{tabular}
\end{minipage}
\parbox{0.97\textwidth}{\scriptsize ARROW-T uses FineCops' structured target noun as its explicit canonical cue. These full-test descriptive rows are not input-matched comparisons to expression-only systems and are not additional confirmatory families.}
\end{table*}
"""
    write_supp_table("supp_finecops_subgroups", body, reg)


def supplement_intervention_table(reg: Registry) -> None:
    reg.reset_used()
    labels = (
        ("Full geometry + full rank + bound support", "p0_s0"),
        ("Canonical geometry", "p1"),
        ("Generic-object geometry", "p2"),
        ("Canonical ranking text", "p3"),
        ("Bound support, different loader draw", "s1"),
        ("Same-category support shuffle", "s2"),
        ("Wrong-category support", "s3"),
        ("Zero support", "s4"),
    )
    rows = []
    for label, row in labels:
        prefix = f"intervention.{row}"
        values = [
            pct(reg.value(f"{prefix}.acc50")),
            pct(reg.value(f"{prefix}.all_query_oracle_recall50")),
            pct(reg.value(f"{prefix}.eligible_recall50")),
            f"{reg.value(f'{prefix}.eligible_query_count_mean'):.1f}",
            f"{reg.value(f'{prefix}.eligible_mask_hamming_mean'):.1f}",
            pct(reg.value(f"{prefix}.top1_query_churn")),
        ]
        rows.append(" & ".join((label, *values)) + r" \\")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Zero-training prompt and support interventions on the fixed seed-42 Val3 surface. Geometry prompts alter the candidate universe; ranking-text and support interventions keep the full-expression geometry path unless named otherwise.}
\label{tab:supp-interventions}
\scriptsize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{lrrrrrr}\toprule
Intervention & Acc$\uparrow$ & All-oracle$\uparrow$ & Elig.-recall$\uparrow$ & Elig. $n$ & Mask $\Delta$ & Top-1 churn\\\midrule
""" + "\n".join(rows) + r"""
\bottomrule\end{tabular}
\end{table*}
"""
    write_supp_table("supp_input_interventions", body, reg)


def supplement_strong_ownership_table(reg: Registry) -> None:
    reg.reset_used()

    def seed_value(key: str, seed: int | None) -> float:
        item = reg.item(key)
        if seed is None:
            return float(item["value"])
        return float(item["by_seed"][str(seed)])

    rows = []
    for route, label in (
        ("native", "Native e5"),
        ("shared_128", "Shared-128"),
        ("shared_wide", "Shared-Wide"),
        ("isolated_128", "Isolated"),
    ):
        seeds = (None,) if route == "native" else (17, 42, 73)
        for seed in seeds:
            if route.startswith("shared"):
                cosine = reg.value(
                    f"strong_ownership.{route}.seed{seed}.cosine_mean"
                )
                cosine_cell = f"{cosine:+.4f}"
            elif route == "isolated_128":
                cosine_cell = "zero"
            else:
                cosine_cell = "--"
            rows.append(" & ".join((
                label,
                "--" if seed is None else str(seed),
                pct(seed_value(f"strong_ownership.{route}.val", seed), 3),
                pct(seed_value(f"strong_ownership.{route}.testa", seed), 3),
                pct(seed_value(f"strong_ownership.{route}.testb", seed), 3),
                pct(seed_value(f"strong_ownership.{route}.testab", seed), 3),
                pct(seed_value(f"strong_ownership.{route}.strict_fpr95", seed), 3),
                pct(seed_value(f"strong_ownership.{route}.strict_auroc", seed), 3),
                pct(seed_value(f"strong_ownership.{route}.strict_aupr", seed), 3),
                cosine_cell,
            )) + r" \\")
    official = (
        pct(reg.value("strong_ownership.official.refcoco_val"), 1),
        pct(reg.value("strong_ownership.official.refcoco_testA"), 1),
        pct(reg.value("strong_ownership.official.refcoco_testB"), 1),
    )
    gradient_rows = []
    for route, label in (("shared_128", "Shared-128"), ("shared_wide", "Shared-Wide")):
        for seed in (17, 42, 73):
            gradient_rows.append(" & ".join((
                label,
                str(seed),
                *(f"{reg.value(f'strong_ownership.{route}.seed{seed}.u{update}.cosine_mean'):+.3f}"
                  for update in (25, 50, 100, 150)),
            )) + r" \\")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Capacity-controlled transfer on the frozen MM-GDINO-T RefCOCO e5
trunk.  Val is mechanism-only; TestAB is the micro average of TestA and TestB.
Strict columns use Strict-TN2031.  The published MMDetection reference is
Val/TestA/TestB=""" + "/".join(official) + r"""; it is not a local-forward row.}
\label{tab:supp-strong-ownership}
\scriptsize
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{lrrrrrrrrr}
\toprule
Route & Seed & Val & TestA & TestB & TestAB & FPR95$\downarrow$ & AUROC$\uparrow$ & AUPR$\uparrow$ & Grad. cos.\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\par\medskip
\textbf{Shared-trunk gradient trajectory}\par\smallskip
\begin{tabular}{lrrrrr}
\toprule
Route & Seed & U25 & U50 & U100 & U150\\
\midrule
""" + "\n".join(gradient_rows) + r"""
\bottomrule
\end{tabular}
\parbox{0.98\textwidth}{\scriptsize All learned rows use the fixed
preregistered endpoint, FP32, clip 0.1, and AdamW with zero weight decay. Rank and rejection
have separate optimizer states in every arm; Shared arms intentionally point
those states at the same trunk parameters. Shared-128 has 50,308 parameters
and 49,536 MAC/query; Shared-Wide has 100,362 and 99,424; Isolated has 100,358
and 98,816. Confidence never selects a query or box. Each Strict bootstrap
replicate recomputes its positive q05.}
\end{table*}
"""
    write_supp_table("supp_strong_ownership", body, reg)


def supplement_strong_e6_ownership_table(reg: Registry) -> None:
    reg.reset_used()

    def seed_value(key: str, seed: int) -> float:
        return float(reg.item(key)["by_seed"][str(seed)])

    result_rows = []
    for trunk, trunk_label in (
        ("e6_posctrl", "e6 PosCtrl"),
        ("e6_tn10", "e6 TN10"),
    ):
        for route, route_label in (
            ("shared_wide", "Shared-Wide"),
            ("isolated_128", "Isolated"),
        ):
            for seed in (17, 42, 73):
                result_rows.append(" & ".join((
                    trunk_label, route_label, {17: "A", 42: "B", 73: "C"}[seed],
                    pct(seed_value(f"strong_e6.{trunk}.{route}.testa", seed), 3),
                    pct(seed_value(f"strong_e6.{trunk}.{route}.testb", seed), 3),
                    pct(seed_value(f"strong_e6.{trunk}.{route}.testab", seed), 3),
                    pct(
                        seed_value(
                            f"strong_e6.{trunk}.{route}.strict_fpr95", seed
                        ),
                        3,
                    ),
                )) + r" \\")

    gradient_rows = []
    for trunk, trunk_label in (
        ("e6_posctrl", "e6 PosCtrl"),
        ("e6_tn10", "e6 TN10"),
    ):
        for horizon, horizon_label in (
            ("all_milestones", "all audit milestones"),
            ("u150", "final endpoint"),
        ):
            prefix = f"strong_e6.{trunk}.shared_wide.{horizon}"
            gradient_rows.append(" & ".join((
                trunk_label,
                horizon_label,
                f"{reg.value(f'{prefix}.mean'):+.4f}",
                pct(reg.value(f"{prefix}.p_negative"), 1),
                f"{reg.value(f'{prefix}.q05'):+.4f}",
                f"{reg.value(f'{prefix}.minimum'):+.4f}",
            )) + r" \\")

    contrast_rows = []
    for trunk, trunk_label in (
        ("e6_posctrl", "e6 PosCtrl"),
        ("e6_tn10", "e6 TN10"),
    ):
        prefix = f"strong_e6.{trunk}.contrast.isolated_vs_shared_wide"
        rec = reg.item(f"{prefix}.rec_gain")
        fpr = reg.item(f"{prefix}.fpr95_gain")
        contrast_rows.append(" & ".join((
            trunk_label,
            rf"{signed_pp(rec['value'], 3)} [{pct(rec['ci95'][0], 3)}, {pct(rec['ci95'][1], 3)}]",
            rf"{signed_pp(fpr['value'], 3)} [{pct(fpr['ci95'][0], 3)}, {pct(fpr['ci95'][1], 3)}]",
            f"{reg.value(f'{prefix}.holm_iut_p'):.4f}",
        )) + r" \\")

    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Strong-trunk continuation stress test.  The original e5 result is the
reference in Tab.~\ref{tab:supp-strong-ownership}; this block runs only the
capacity-matched Shared-Wide/Isolated pair at the fixed U150 endpoint.}
\label{tab:supp-strong-e6-ownership}
\scriptsize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{lllrrrr}
\toprule
Frozen trunk & Owner & Seed ID & TestA & TestB & TestAB & FPR95$\downarrow$\\
\midrule
""" + "\n".join(result_rows) + r"""
\bottomrule
\end{tabular}
\par\medskip
\begin{tabular}{llrrrr}
\toprule
Frozen trunk & Probe horizon & Mean cosine & $P(\cos<0)$ & q05 & Minimum\\
\midrule
""" + "\n".join(gradient_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrrr}
\toprule
Frozen trunk & Isolated$-$Shared REC [CI] & FPR95 reduction [CI] & Holm-IUT $p$\\
\midrule
""" + "\n".join(contrast_rows) + r"""
\bottomrule
\end{tabular}
\parbox{0.98\textwidth}{\scriptsize Percentages except gradient statistics.
Positive FPR95 reduction favors Isolated.  The same image-cluster draw is used
for both trunks, owners, and all seeds; every replicate recomputes each
positive q05.  TN10 deepens the negative tail but does not improve Isolated
REC, and its rejection interval favors Shared-Wide.}
\end{table*}
"""
    write_supp_table("supp_strong_e6_ownership", body, reg)


def supplement_pretrain_ownership_table(reg: Registry) -> None:
    reg.reset_used()

    def seed_value(key: str, seed: int) -> float:
        return float(reg.item(key)["by_seed"][str(seed)])

    result_rows = []
    for route, label in (("shared_wide", "Shared-Wide"), ("isolated_128", "Isolated")):
        for seed in (17, 42, 73):
            result_rows.append(" & ".join((
                label, {17: "A", 42: "B", 73: "C"}[seed],
                pct(seed_value(f"strong_pretrain.{route}.test5", seed), 3),
                pct(seed_value(f"strong_pretrain.{route}.testab", seed), 3),
                pct(seed_value(f"strong_pretrain.{route}.strict_fpr95", seed), 3),
                pct(seed_value(f"strong_pretrain.{route}.strict_auroc", seed), 3),
                pct(seed_value(f"strong_pretrain.{route}.strict_aupr", seed), 3),
            )) + r" \\")

    split_rows = []
    for route, label in (("shared_wide", "Shared-Wide"), ("isolated_128", "Isolated")):
        split_rows.append(" & ".join((
            label,
            *(
                pct(reg.value(f"strong_pretrain.{route}.{split}"), 3)
                for split in (
                    "refcoco_testA", "refcoco_testB", "refcocop_testA",
                    "refcocop_testB", "refcocog_test",
                )
            ),
        )) + r" \\")

    gradient_rows = []
    for horizon, label in (
        ("all_milestones", "all milestones"),
        ("u150", "final endpoint"),
    ):
        prefix = f"strong_pretrain.shared_wide.{horizon}"
        gradient_rows.append(" & ".join((
            label,
            str(int(reg.value(f"{prefix}.count"))),
            f"{reg.value(f'{prefix}.mean'):+.4f}",
            pct(reg.value(f"{prefix}.p_negative"), 1),
            f"{reg.value(f'{prefix}.q05'):+.4f}",
            f"{reg.value(f'{prefix}.minimum'):+.4f}",
        )) + r" \\")

    prefix = "strong_pretrain.contrast.isolated_vs_shared_wide"
    test5 = reg.item(f"{prefix}.test5_gain")
    testab = reg.item(f"{prefix}.testab_gain")
    fpr = reg.item(f"{prefix}.fpr95_gain")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{MM-GDINO-T pretrained-trunk ownership replay.  The trunk has broad
grounding pretraining but no RefCOCO-specific full-model fine-tuning; only the
capacity-matched Shared-Wide/Isolated pair is trained at fixed U150.}
\label{tab:supp-pretrain-ownership}
\scriptsize
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{llrrrrr}
\toprule
Owner & Seed & Test5 & TestAB & FPR95$\downarrow$ & AUROC$\uparrow$ & AUPR$\uparrow$\\
\midrule
""" + "\n".join(result_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrrrrr}
\toprule
Owner & RefCOCO A & RefCOCO B & RefCOCO+ A & RefCOCO+ B & RefCOCOg\\
\midrule
""" + "\n".join(split_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrrrrr}
\toprule
Probe horizon & $n$ & Mean cosine & $P(\cos<0)$ & q05 & Minimum\\
\midrule
""" + "\n".join(gradient_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrr}
\toprule
Endpoint & Isolated$-$Shared [95\% CI] & Interpretation\\
\midrule
Test5 & """ + rf"{signed_pp(test5['value'], 3)} [{pct(test5['ci95'][0], 3)}, {pct(test5['ci95'][1], 3)}]" + r""" & Shared-Wide higher\\
TestAB & """ + rf"{signed_pp(testab['value'], 3)} [{pct(testab['ci95'][0], 3)}, {pct(testab['ci95'][1], 3)}]" + r""" & Shared-Wide higher\\
FPR95 reduction & """ + rf"{signed_pp(fpr['value'], 3)} [{pct(fpr['ci95'][0], 3)}, {pct(fpr['ci95'][1], 3)}]" + r""" & interval crosses zero\\
\bottomrule
\end{tabular}
\parbox{0.98\textwidth}{\scriptsize Percentages except gradient statistics.
FPR95 reduction is Shared-Wide minus Isolated, hence positive values favor
Isolated. Statistics use """ + f"{int(reg.value('strong_pretrain.bootstrap.replicates')):,}" + r""" paired image-cluster bootstrap replicates; every
FPR95 replicate recomputes each route/seed positive q05. The five Test5 split
means are three-seed means. Isolated has no cross-task autograd path.}
\end{table*}
"""
    write_supp_table("supp_pretrain_ownership", body, reg)


def supplement_original_parent_ownership_table(reg: Registry) -> None:
    reg.reset_used()

    def seed_value(key: str, seed: int) -> float:
        return float(reg.item(key)["by_seed"][str(seed)])

    result_rows = [" & ".join((
        "Native", "--",
        pct(reg.value("original_parent.native.test5"), 3),
        pct(reg.value("original_parent.native.testab"), 3),
        pct(reg.value("original_parent.native.strict_fpr95"), 3),
        pct(reg.value("original_parent.native.strict_auroc"), 3),
        pct(reg.value("original_parent.native.strict_aupr"), 3),
    )) + r" \\"]
    for route, label in (("shared_wide", "Shared-Wide"), ("isolated_128", "Isolated")):
        for seed in (17, 42, 73):
            result_rows.append(" & ".join((
                label, {17: "A", 42: "B", 73: "C"}[seed],
                pct(seed_value(f"original_parent.{route}.test5", seed), 3),
                pct(seed_value(f"original_parent.{route}.testab", seed), 3),
                pct(seed_value(f"original_parent.{route}.strict_fpr95", seed), 3),
                pct(seed_value(f"original_parent.{route}.strict_auroc", seed), 3),
                pct(seed_value(f"original_parent.{route}.strict_aupr", seed), 3),
            )) + r" \\")

    split_rows = []
    for route, label in (
        ("native", "Native"),
        ("shared_wide", "Shared-Wide"),
        ("isolated_128", "Isolated"),
    ):
        split_rows.append(" & ".join((
            label,
            *(
                pct(reg.value(f"original_parent.{route}.{split}"), 3)
                for split in (
                    "refcoco_testA", "refcoco_testB", "refcocop_testA",
                    "refcocop_testB", "refcocog_test",
                )
            ),
        )) + r" \\")

    gradient_rows = []
    for horizon, label in (
        ("all_milestones", "all milestones"),
        ("u150", "final endpoint"),
    ):
        prefix = f"original_parent.shared_wide.{horizon}"
        gradient_rows.append(" & ".join((
            label,
            str(int(reg.value(f"{prefix}.count"))),
            f"{reg.value(f'{prefix}.mean'):+.4f}",
            pct(reg.value(f"{prefix}.p_negative"), 1),
            f"{reg.value(f'{prefix}.q05'):+.4f}",
            f"{reg.value(f'{prefix}.minimum'):+.4f}",
        )) + r" \\")

    prefix = "original_parent.contrast.isolated_vs_shared_wide"
    test5 = reg.item(f"{prefix}.test5_gain")
    testab = reg.item(f"{prefix}.testab_gain")
    fpr = reg.item(f"{prefix}.fpr95_gain")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Direct pre-Stage-B GroundingDINO parent ownership replay.  Native,
Shared-Wide, and Isolated use identical frozen candidates and the
full-expression mean score; learned routes use the fixed endpoint.}
\label{tab:supp-original-parent-ownership}
\scriptsize
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{llrrrrr}
\toprule
Owner & Seed & Test5 & TestAB & FPR95$\downarrow$ & AUROC$\uparrow$ & AUPR$\uparrow$\\
\midrule
""" + "\n".join(result_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrrrrr}
\toprule
Owner & RefCOCO A & RefCOCO B & RefCOCO+ A & RefCOCO+ B & RefCOCOg\\
\midrule
""" + "\n".join(split_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrrrrr}
\toprule
Probe horizon & $n$ & Mean cosine & $P(\cos<0)$ & q05 & Minimum\\
\midrule
""" + "\n".join(gradient_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrr}
\toprule
Endpoint & Isolated$-$Shared [95\% CI] & Interpretation\\
\midrule
Test5 & """ + rf"{signed_pp(test5['value'], 3)} [{pct(test5['ci95'][0], 3)}, {pct(test5['ci95'][1], 3)}]" + r""" & Isolated fails non-inferiority\\
TestAB & """ + rf"{signed_pp(testab['value'], 3)} [{pct(testab['ci95'][0], 3)}, {pct(testab['ci95'][1], 3)}]" + r""" & Isolated fails non-inferiority\\
FPR95 reduction & """ + rf"{signed_pp(fpr['value'], 3)} [{pct(fpr['ci95'][0], 3)}, {pct(fpr['ci95'][1], 3)}]" + r""" & interval crosses zero\\
\bottomrule
\end{tabular}
\parbox{0.98\textwidth}{\scriptsize Percentages except gradient statistics.
FPR95 reduction is Shared-Wide minus Isolated. Statistics use """ + f"{int(reg.value('original_parent.bootstrap.replicates')):,}" + r""" paired image-cluster
replicates and recompute every positive q05. The direct-parent raw-query owners
have 100,362/100,358 parameters; the existing frozen-base integrated owners have
83,971/83,969.  This table alone is not a cross-stage contrast; the strict
same-100k-head adapted replay is reported in the next table.}
\end{table*}
"""
    write_supp_table("supp_original_parent_ownership", body, reg)


def supplement_b58_raw_query_ownership_table(reg: Registry) -> None:
    reg.reset_used()

    def seed_value(key: str, seed: int) -> float:
        return float(reg.item(key)["by_seed"][str(seed)])

    result_rows = [" & ".join((
        "Native", "--",
        pct(reg.value("b58_raw_query.native.test5"), 3),
        pct(reg.value("b58_raw_query.native.testab"), 3),
        pct(reg.value("b58_raw_query.native.strict_fpr95"), 3),
        pct(reg.value("b58_raw_query.native.strict_auroc"), 3),
        pct(reg.value("b58_raw_query.native.strict_aupr"), 3),
    )) + r" \\"]
    for route, label in (("shared_wide", "Shared-Wide"), ("isolated_128", "Isolated")):
        for seed in (17, 42, 73):
            result_rows.append(" & ".join((
                label, {17: "A", 42: "B", 73: "C"}[seed],
                pct(seed_value(f"b58_raw_query.{route}.test5", seed), 3),
                pct(seed_value(f"b58_raw_query.{route}.testab", seed), 3),
                pct(seed_value(f"b58_raw_query.{route}.strict_fpr95", seed), 3),
                pct(seed_value(f"b58_raw_query.{route}.strict_auroc", seed), 3),
                pct(seed_value(f"b58_raw_query.{route}.strict_aupr", seed), 3),
            )) + r" \\")

    gradient_rows = []
    for horizon, label in (("all_milestones", "all milestones"), ("u150", "final endpoint")):
        prefix = f"b58_raw_query.shared_wide.{horizon}"
        gradient_rows.append(" & ".join((
            label,
            str(int(reg.value(f"{prefix}.count"))),
            f"{reg.value(f'{prefix}.mean'):+.4f}",
            pct(reg.value(f"{prefix}.p_negative"), 1),
            f"{reg.value(f'{prefix}.q05'):+.4f}",
            f"{reg.value(f'{prefix}.minimum'):+.4f}",
        )) + r" \\")

    did_rows = []
    for endpoint, label in (
        ("test5", "Test5 ownership effect"),
        ("testab", "TestAB ownership effect"),
        ("fpr95_reduction", "FPR95-reduction ownership effect"),
    ):
        item = reg.item(f"parent_to_b58_did.{endpoint}")
        did_rows.append(" & ".join((
            label,
            signed_pp(item["value"], 3),
            rf"[{pct(item['ci95'][0], 3)}, {pct(item['ci95'][1], 3)}]",
            "excludes zero" if item["ci95"][0] > 0.0 else "crosses zero",
        )) + r" \\")

    prefix = "b58_raw_query.contrast.isolated_vs_shared_wide"
    test5 = reg.item(f"{prefix}.test5_gain")
    testab = reg.item(f"{prefix}.testab_gain")
    fpr = reg.item(f"{prefix}.fpr95_gain")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Strict same-100k-head adapted-trunk replay and direct-parent difference-in-differences.}
\label{tab:supp-same-head-stage-axis}
\scriptsize
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{llrrrrr}
\toprule
Owner & Seed & Test5 & TestAB & FPR95$\downarrow$ & AUROC$\uparrow$ & AUPR$\uparrow$\\
\midrule
""" + "\n".join(result_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrrrrr}
\toprule
Probe horizon & $n$ & Mean cosine & $P(\cos<0)$ & q05 & Minimum\\
\midrule
""" + "\n".join(gradient_rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{lrrl}
\toprule
Parent$\rightarrow$adapted DiD & Effect & 95\% CI & Decision\\
\midrule
""" + "\n".join(did_rows) + r"""
\bottomrule
\end{tabular}
\parbox{0.98\textwidth}{\scriptsize Adapted-trunk Isolated$-$Shared:
Test5 """ + rf"{signed_pp(test5['value'], 3)} [{pct(test5['ci95'][0], 3)}, {pct(test5['ci95'][1], 3)}]" + r""",
TestAB """ + rf"{signed_pp(testab['value'], 3)} [{pct(testab['ci95'][0], 3)}, {pct(testab['ci95'][1], 3)}]" + r""";
FPR95 reduction """ + rf"{signed_pp(fpr['value'], 3)} [{pct(fpr['ci95'][0], 3)}, {pct(fpr['ci95'][1], 3)}]" + r""".
All values are percentages or percentage points except cosine.  The 5,000
paired image-cluster replicates use the same draw across parent/adapted trunks, owners,
and seeds and recompute every positive q05.}
\end{table*}
"""
    write_supp_table("supp_same_head_stage_axis", body, reg)


def supplement_b58_capacity_table(reg: Registry) -> None:
    reg.reset_used()
    rows = []
    for arm, label in (("shared_wide", "Shared-Wide"), ("isolated", "Isolated replay")):
        for seed in (17, 42, 73):
            if arm == "shared_wide":
                cosine = f"{reg.value(f'b58_capacity.shared_wide.seed{seed}.cosine_mean'):+.3f}"
                negative = pct(
                    reg.value(f"b58_capacity.shared_wide.seed{seed}.negative_cosine_fraction"),
                    1,
                )
            else:
                cosine, negative = "zero", "0.0"
            rows.append(" & ".join((
                label,
                str(seed),
                pct(reg.value(f"b58_capacity.{arm}.seed{seed}.test5"), 3),
                pct(reg.value(f"b58_capacity.{arm}.seed{seed}.fpr95"), 3),
                pct(reg.value(f"b58_capacity.{arm}.seed{seed}.auroc"), 3),
                pct(reg.value(f"b58_capacity.{arm}.seed{seed}.positive_aupr"), 3),
                cosine,
                negative,
            )) + r" \\")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{ARROW-U2 capacity/optimizer-matched ownership control. Shared-Wide and
Isolated differ by two score-owner parameters; both use two task-specific
AdamW states, zero weight decay, and fixed U150 endpoints.}
\label{tab:supp-arrow-capacity}
\scriptsize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{llrrrrrr}\toprule
Owner & Seed & Test5 & Strict FPR95 & AUROC & AUPR & Grad. cosine & Neg. cosine (\%)\\\midrule
""" + "\n".join(rows) + r"""
\bottomrule\end{tabular}
\parbox{0.98\textwidth}{\scriptsize The paired Test5 gain of Isolated is
5.311 points (95\% image-cluster CI [4.875, 5.768]).  The paired Strict
FPR95 reduction is 0.689 points (CI [$-0.382$, 1.337], one-sided
$p=0.139$), so the preregistered joint gate does not pass.  Every bootstrap
replicate recomputes each arm/seed's positive q05 threshold.}
\end{table*}
"""
    write_supp_table("supp_arrow_capacity_control", body, reg)


def supplement_strong_baseline_table(reg: Registry) -> None:
    reg.reset_used()
    rows = (
        (
            "MM-GDINO-T 5e (model zoo)",
            pct(reg.value("strong_ownership.official.refcoco_val"), 2),
            pct(reg.value("strong_ownership.official.refcoco_testA"), 2),
            pct(reg.value("strong_ownership.official.refcoco_testB"), 2),
        ),
        (
            "Local epoch-5 frozen replay",
            pct(reg.value("strong_ownership.native.val"), 2),
            pct(reg.value("strong_ownership.native.testa"), 2),
            pct(reg.value("strong_ownership.native.testb"), 2),
        ),
    )
    body_rows = "\n".join(" & ".join(row) + r" \\" for row in rows)
    body = rf"""% Generated by paper/scripts/make_main_tables.py.
\begin{{table}}[t]
\centering
\caption{{Strong RefCOCO localization scale check. These standard split
scores are not the five-split Test5 endpoint and are not an ARROW superiority
contrast.}}
\label{{tab:supp-strong-baseline}}
\scriptsize
\setlength{{\tabcolsep}}{{4.2pt}}
\begin{{tabular}}{{lrrr}}\toprule
Evidence source & Val & TestA & TestB\\\midrule
{body_rows}
\bottomrule\end{{tabular}}
\parbox{{0.96\columnwidth}}{{\scriptsize P@1 at IoU$\geq0.5$ (\%). The
published row is a model-zoo reference, not a local forward. The local row is
recomputed from the exact frozen epoch-5 state (SHA-256 prefix
\texttt{{2ec6fbc0}}). Its training configuration evaluated Val/TestA/TestB
every epoch, so it is a retrospective replay rather than virgin held-out
evidence.}}
\end{{table}}
"""
    write_supp_table("supp_strong_baseline", body, reg)


def supplement_cross_dataset_probe_table(reg: Registry) -> None:
    reg.reset_used()
    rows = []
    cosine_rows = []
    for route, route_label in (("shared_128", "Shared-128"), ("shared_wide", "Shared-Wide")):
        for dataset, dataset_label in (
            ("refcoco", "RefCOCO"),
            ("refcocoplus", "RefCOCO+"),
            ("refcocog", "RefCOCOg"),
        ):
            prefix = f"strong_cross_probe.{route}.{dataset}"
            rows.append(" & ".join((
                route_label,
                dataset_label,
                f"{reg.value(f'{prefix}.cosine'):+.4f}",
                f"{reg.value(f'{prefix}.sign_conflict_fraction'):.4f}",
                f"{reg.value(f'{prefix}.rank_gradient_l2'):.4f}",
                f"{reg.value(f'{prefix}.confidence_gradient_l2'):.4f}",
                pct(reg.value(f"{prefix}.native_p1"), 2),
                f"{reg.value(f'{prefix}.rank_loss'):.4f}",
                f"{reg.value(f'{prefix}.native_top1_runnerup_margin'):.4f}",
                f"{reg.value(f'{prefix}.native_oracle_positive_negative_gap'):.4f}",
            )) + r" \\")
            cosine_rows.append(" & ".join((
                route_label,
                dataset_label,
                *(f"{reg.value(f'{prefix}.seed{seed}.cosine'):+.4f}" for seed in (17, 42, 73)),
            )) + r" \\")
    body = r"""% Generated by paper/scripts/make_main_tables.py.
\begin{table*}[t]
\centering
\caption{Zero-update rank-dataset probe on the same RefCOCO-e5 trunk and U150
shared checkpoints.  Only the rank batch changes; each route/seed reuses the
same eight formal D3 confidence batches and sealed queue.  All values are
three-seed means except the lower seed table.}
\label{tab:supp-cross-dataset-probe}
\scriptsize
\setlength{\tabcolsep}{2.6pt}
\begin{tabular}{llrrrrrrrr}
\toprule
Owner & Rank data & Cos. & Sign-conf. & $\lVert g_R\rVert$ & $\lVert g_C\rVert$ & Native P@1 & Rank loss & Top1 margin & Oracle gap\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\par\smallskip
\begin{tabular}{llrrr}
\toprule
Owner & Rank data & seed17 cosine & seed42 cosine & seed73 cosine\\
\midrule
""" + "\n".join(cosine_rows) + r"""
\bottomrule
\end{tabular}
\parbox{0.98\textwidth}{\scriptsize P@1 and both margins use the frozen native
query scores. Top1 margin is the best-minus-runner-up valid-query score;
oracle gap is the best IoU-positive minus best IoU-negative score. No optimizer
is created, all checkpoint tensor hashes are unchanged, and confidence-gradient
fingerprints are identical across the three rank datasets.}
\end{table*}
"""
    write_supp_table("supp_cross_dataset_probe", body, reg)


def main() -> None:
    reg = Registry()
    table1(reg)
    table2(reg)
    table3(reg)
    table4(reg)
    supplement_cumulative_routes(reg)
    supplement_training_table(reg)
    supplement_ref_breakdown_table(reg)
    supplement_gap_table(reg)
    supplement_finecops_subgroup_table(reg)
    supplement_intervention_table(reg)
    supplement_strong_baseline_table(reg)
    supplement_strong_ownership_table(reg)
    supplement_strong_e6_ownership_table(reg)
    supplement_pretrain_ownership_table(reg)
    supplement_original_parent_ownership_table(reg)
    supplement_b58_raw_query_ownership_table(reg)
    supplement_b58_capacity_table(reg)
    supplement_cross_dataset_probe_table(reg)
    number_macros(reg)


if __name__ == "__main__":
    main()
